=begin comment

Web API Swagger specification

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('AsposeDiagramCloud::OAuthApi');
use_ok('AsposeDiagramCloud::Configuration');
use_ok('AsposeDiagramCloud::ApiClient');

my $config = AsposeDiagramCloud::Configuration->new('base_url' => 'https://api.aspose.cloud/');
my $client = AsposeDiagramCloud::ApiClient->new( $config);
my $api = AsposeDiagramCloud::OAuthApi->new($client);
isa_ok($api, 'AsposeDiagramCloud::OAuthApi');

my $access_token;
#
# o_auth_post test
#
{
    my $grant_type = 'client_credentials'; # replace NULL with a proper value
    my $client_id = '66164C51-693E-4904-A121-545961673EC1'; # replace NULL with a proper value
    my $client_secret =  '536e76768419db9585afdd37bb5f7533'; # replace NULL with a proper value
    my $result = $api->o_auth_post(grant_type => $grant_type, client_id => $client_id, client_secret => $client_secret);
    $access_token =  $result->access_token;
    printf $access_token;
}
printf "\n";

1;
