=begin comment

Web API Swagger specification

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#

use lib 'lib';
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);
#use File::Slurp;

use AsposeDiagramCloud::OAuthApi ;
use AsposeDiagramCloud::Configuration ;
use AsposeDiagramCloud::ApiClient ;
use AsposeDiagramCloud::Object::SaaSposeResponse ;
# sub new {
#     my $class = shift;
#     return bless {}, $class;
# }
our $new_client = undef;

my $grant_type = 'client_credentials'; # replace NULL with a proper value
my $client_id = 'yourClientId'; # replace NULL with a proper value
my $client_secret =  'yourClientSecret'; # replace NULL with a proper value

sub get_diagram_api
{
    my ($self, %args) = @_;
    my $config = AsposeDiagramCloud::Configuration->new('base_url' => 'https://api.aspose.cloud','api_version' => 'v3.0', app_sid => $client_id, app_key => $client_secret);
    my $client = AsposeDiagramCloud::ApiClient->new( $config);
    my $diagram_api = AsposeDiagramCloud::DiagramApi->new($client);
    return $diagram_api;
}

sub get_storage_api
{
    my ($self, %args) = @_;
    my $config = AsposeDiagramCloud::Configuration->new('base_url' => 'https://api.aspose.cloud','api_version' => 'v3.0', app_sid => $client_id, app_key => $client_secret);
    my $client = AsposeDiagramCloud::ApiClient->new( $config);
    my $diagram_api = AsposeDiagramCloud::StorageApi->new($client);
    return $diagram_api;
}

1;
