=begin comment

Web API Swagger specification

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#

use lib 'lib';
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use AsposeDiagramCloud::OAuthApi ;
use AsposeDiagramCloud::Configuration ;
use AsposeDiagramCloud::ApiClient ;
use AsposeDiagramCloud::Object::SaaSposeResponse ;
# sub new {
#     my $class = shift;
#     return bless {}, $class;
# }
our $new_client = undef;

sub get_client
{
    my ($self, %args) = @_;
    my $config = AsposeDiagramCloud::Configuration->new('base_url' => 'https://api.aspose.cloud/');
    my $client = AsposeDiagramCloud::ApiClient->new( $config);
    my $oauth_api = AsposeDiagramCloud::OAuthApi->new($client);

    my $grant_type = 'client_credentials'; # replace NULL with a proper value
    my $client_id = 'xxxxxxxx'; # replace NULL with a proper value
    my $client_secret =  'xxxxxxxxxx'; # replace NULL with a proper value
    my $result = $oauth_api->o_auth_post(grant_type => $grant_type, client_id => $client_id, client_secret => $client_secret);
    my $access_token  = $result->access_token;

    my $new_config = AsposeDiagramCloud::Configuration->new('access_token' =>  $access_token, 'base_url' => 'https://api.aspose.cloud/v1.1');
    $new_client = AsposeDiagramCloud::ApiClient->new( $new_config);
    return $new_client;
}

1;
